language: java
jdk:
  - openjdk11

get:
  depth: false

stages:
- "unit test and scan"
- "integration test"

install:
  - mvn clean versions:set -DnewVersion=1.0.${TRAVIS_BUILD_NUMBER}

jobs:
  allow_failures: 
  - script: mvn install sonar:sonar -Dsonar.projectKey=slt-programmers_macrologBackend
  include: 
  - stage: "unit test and scan"
    if: branch != release
    script: mvn install
  - stage: "unit test and scan"
    if: branch != release
    script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=slt-programmers_macrologBackend
  - stage: "integration test"
    if: branch = release
    script: mvn install
    
# Integration test has yet to be defined, for now just mvn install
# Autodeploy is done by Heroku

addons:
  sonarcloud:
    organization: "slt-programmers"
    token:
      secure: "nmgPEP8Rojw28zNlO3t3M0kx9ZxipG1AsZxXmNuXZlBTveu9W9k3ksgU76csprfr305/pmUI/D21Bz/rQpolpg1iXKbWxHLKLfQKhZECcwTQXJhmZusbuEBfxN1mi9bmePBU2c9PAb4UoGX/CfcfNcREpeROfNpoXNcoq4goTfQTMqRLuhhGNHH7CWBVUDcaXjCn2NiaxjlGzLzNOiuav4P+URDCstpx9LJw4Uz3485OM3KrhsYjkVBFcXE2WhlSCLXeR9xXv+KddJJBLhQgrWPwD9n3GKndI5yDxHn9NfqepOcM+cwPlU0LKQ0R7MH+GtYn+ooaS/HqCmnC+6jf3tBaNpP8tZkgM3VZulUqLLIsTYTLm74GAz9lrSuRr4fcWeFSt95+SGaJT5xDEkJZS59BmZGC88HC48Hlz0rJ68deWgySwPDI8/GImFgH5vaLxuxAyyncriSV7vDB/AT3jBvoL5pkoQNci75kJgyJoHCK6QpcgABRotGS7yx3cAdB/tbNL7/J9dIZorFtp142Ry7OCwnqcqzRzqTzgUcn4xvvY9ptG4j09EZfVrG3le336ndQhSekp7HL9UkrW2LhE87aWydOXmmh1082vloDN4P2qenQC7k765obZVwd1V73Ayi0O4ZQnTO1KB/mjGakxxrFyxa9/KOVlOtqJXdceno="

notifications:
  slack: homeworkcarmenarjan:YreL13iWQ3xpqtXLpudbTy2m
